apiVersion: v1
kind: Service
metadata:
  name: mongodb-2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-2
  ports:
    - port: 27017
      targetPort: 27017
