apiVersion: v1
kind: Service
metadata:
  name: mongo-app-on-container-example

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000

  selector:
    pod-name: mongo-app-on-container-example-pod
